# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VF36KX966fMWSSnob7ahbIK4usyMXDNe
"""

from flask import Flask, request, render_template
import joblib

app = Flask(__name__)

# Load the model
model = joblib.load("/content/fish_weight_model.pkl")

@app.route("/")
def home():
    return render_template("index.html")

@app.route("/predict", methods=["POST"])
def predict():
    # Get input data
    features = [float(request.form[field]) for field in ["Length1", "Length2", "Length3", "Height", "Width"]]
    # Make prediction
    prediction = model.predict([features])
    return render_template("index.html", prediction=f"Predicted Weight: {prediction[0]:.2f} g")

if __name__ == "__main__":
    app.run(debug=True)